### ISSUE TITLE
Does it support KMM ?

### ISSUE THREAD

**Issue by 658jjh** [Abhimanyu14/compose-emoji-picker#21]
Does this one support KMM @Abhimanyu14  ?

**Comment by Abhimanyu14** [comment]
Hi @658jjh,

If you are referring to Compose MultiPlatform (CMP), then this library does not support CMP yet.

For the logic part, the core logic is extracted into a separate library (https://github.com/Abhimanyu14/emoji-core).    
It is a pure Kotlin library and is KMP-compatible.
