### ISSUE TITLE
Fetching emojis

### ISSUE THREAD

**Issue by nizam-betterapp** [Abhimanyu14/compose-emoji-picker#3]
I see that you are using disk caching to save the emojis to be working offline. even when the user is online, why not show the offline emojis first and then update the cache from the internet. This will be useful since it takes a while for users to see the emoji's and the user sees "Fetching Emoji's". if the user is offline, then it's super quick.

Please let me know if you need any clarifications on this issue. Thanks :)

**Comment by Abhimanyu14** [comment]
Hi @nizam-betterapp, 
I am using OkHttp's default caching mechanism. 
I do not have any custom logic.

I tried this from my end and the loading time is not too bad.
Could you kindly share more info if you have any thoughts on what caching optimization can be done to enhance this experience?

**Comment by Abhimanyu14** [comment]
Upon further testing, I noticed that the network call is only made when the cache isn't available.

**Comment by nizam-betterapp** [comment]
Ok. Thanks for the clarification.
