### ISSUE TITLE
jitpack download issue

### ISSUE THREAD

**Issue by nizam-betterapp** [Abhimanyu14/compose-emoji-picker#4]
<img width="1097" alt="Screenshot 2024-03-22 at 10 12 30 AM" src="https://github.com/Abhimanyu14/compose-emoji-picker/assets/128673271/de4d475f-48f1-461a-bdc1-fbbb57832dde">

Can you please throw some light here?

**Comment by nizam-betterapp** [comment]
<img width="948" alt="Screenshot 2024-03-22 at 10 23 20 AM" src="https://github.com/Abhimanyu14/compose-emoji-picker/assets/128673271/eb9456db-6e31-46c4-929b-169c271aab04">

**Comment by Abhimanyu14** [comment]
This is the Jitpack link
https://jitpack.io/#Abhimanyu14/compose-emoji-picker 

You can find this in the Readme
<img width="323" alt="image" src="https://github.com/Abhimanyu14/compose-emoji-picker/assets/29737108/1e52255b-1a82-4210-9c97-75d848938348">

**Comment by Abhimanyu14** [comment]
What is the issue here?
Can you please add more details?

**Comment by nizam-betterapp** [comment]
Looked like a temporary download issue from jitpack for your library's latest version. It's fixed now. I am closing this. Thanks a lot :)
